# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Space.create(:name => "パーティールーム1", :price => 1500, :image =>"", :discription => "駅近でとても綺麗なパーティースペースです", :addres => "東京都渋谷区", :)
Genre.create(:name => "パーティー")
Genre.create(:name => "セミナー")
Genre.create(:name => "合コン")
Genre.create(:name => "スポーツ")
Genre.create(:name => "会議")
Genre.create(:name => "イベント")
Genre.create(:name => "オフィス")
Genre.create(:name => "アウトドア")
Genre.create(:name => "BBQ")
Genre.create(:name => "ロケ撮影")
Genre.create(:name => "写真撮影")
Genre.create(:name => "民泊")
Genre.create(:name => "展示会")
Genre.create(:name => "式典")

TimeCount.create(:time => "0:00 ~ 1:00")
TimeCount.create(:time => "1:00 ~ 2:00")
TimeCount.create(:time => "2:00 ~ 3:00")
TimeCount.create(:time => "3:00 ~ 4:00")
TimeCount.create(:time => "4:00 ~ 5:00")
TimeCount.create(:time => "5:00 ~ 6:00")
TimeCount.create(:time => "6:00 ~ 7:00")
TimeCount.create(:time => "7:00 ~ 8:00")
TimeCount.create(:time => "8:00 ~ 9:00")
TimeCount.create(:time => "9:00 ~ 10:00")
TimeCount.create(:time => "10:00 ~ 11:00")
TimeCount.create(:time => "11:00 ~ 12:00")
TimeCount.create(:time => "12:00 ~ 13:00")
TimeCount.create(:time => "13:00 ~ 14:00")
TimeCount.create(:time => "14:00 ~ 15:00")
TimeCount.create(:time => "15:00 ~ 16:00")
TimeCount.create(:time => "16:00 ~ 17:00")
TimeCount.create(:time => "17:00 ~ 18:00")
TimeCount.create(:time => "18:00 ~ 19:00")
TimeCount.create(:time => "19:00 ~ 20:00")
TimeCount.create(:time => "20:00 ~ 21:00")
TimeCount.create(:time => "21:00 ~ 22:00")
TimeCount.create(:time => "22:00 ~ 23:00")
TimeCount.create(:time => "23:00 ~ 0:00")

Amenitie.create(:name => "ゲーム")
Amenitie.create(:name => "パワーポイント")
Amenitie.create(:name => "モニター")
Amenitie.create(:name => "マイク")
Amenitie.create(:name => "パソコン")
Amenitie.create(:name => "コンセント")
Amenitie.create(:name => "テーブル")
Amenitie.create(:name => "椅子")
Amenitie.create(:name => "プロジェクター")
Amenitie.create(:name => "駐車場")
Amenitie.create(:name => "WI-FI")
Amenitie.create(:name => "ホワイトボード")
Amenitie.create(:name => "プリンター")
Amenitie.create(:name => "キッチン設備")
Amenitie.create(:name => "調理機材")
Amenitie.create(:name => "テレビ")
Amenitie.create(:name => "ロッカー")
Amenitie.create(:name => "ケータリング")
Amenitie.create(:name => "スピーカー")
Amenitie.create(:name => "シャワー")
Amenitie.create(:name => "照明設備")
Amenitie.create(:name => "トイレ")
Amenitie.create(:name => "冷蔵庫")
Amenitie.create(:name => "ミラー")