# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Space.create(:name => "パーティールーム1", :price => 1500, :image =>"", :discription => "駅近でとても綺麗なパーティースペースです", :addres => "東京都渋谷区", :)
Genre.create(:name => "パーティー")
Genre.create(:name => "セミナー")
Genre.create(:name => "合コン")
Genre.create(:name => "スポーツ")
Genre.create(:name => "会議")
Genre.create(:name => "イベント")
Genre.create(:name => "オフィス")
Genre.create(:name => "アウトドア")
Genre.create(:name => "BBQ")
Genre.create(:name => "ロケ撮影")
Genre.create(:name => "写真撮影")
Genre.create(:name => "民泊")
Genre.create(:name => "展示会")
Genre.create(:name => "式典")



Amenitie.create(:name => "ゲーム")
Amenitie.create(:name => "パワーポイント")
Amenitie.create(:name => "モニター")
Amenitie.create(:name => "マイク")
Amenitie.create(:name => "パソコン")
Amenitie.create(:name => "コンセント")
Amenitie.create(:name => "テーブル")
Amenitie.create(:name => "椅子")
Amenitie.create(:name => "プロジェクター")
Amenitie.create(:name => "駐車場")
Amenitie.create(:name => "WI-FI")
Amenitie.create(:name => "ホワイトボード")
Amenitie.create(:name => "プリンター")
Amenitie.create(:name => "キッチン設備")
Amenitie.create(:name => "調理機材")
Amenitie.create(:name => "テレビ")
Amenitie.create(:name => "ロッカー")
Amenitie.create(:name => "ケータリング")
Amenitie.create(:name => "スピーカー")
Amenitie.create(:name => "シャワー")
Amenitie.create(:name => "照明設備")
Amenitie.create(:name => "トイレ")
Amenitie.create(:name => "冷蔵庫")
Amenitie.create(:name => "ミラー")